brew 'coreutils'
brew 'tmux'
brew 'gh'
brew 'git'
brew 'grep'
brew 'ripgrep'
brew 'fd'
brew 'go'
brew 'neovim'
brew 'arduino-cli'
brew 'tree-sitter-cli'
brew 'prettierd'
brew 'lua-language-server'

cask 'alacritty'
cask 'brave-browser'
cask 'font-hack-nerd-font'
